# Run the tests
# Assumes you have installed zkl or set up the runZKL script
# If not, cd to the VM directory and "make test" there 

test :
	(cd ..; zklRoot=$$PWD LD_LIBRARY_PATH=Lib Bin/zkl Test.testThemAll -R Tests)
